# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

puttmaster = Player.create(name: "Puttmaster1")

ballyneal = Course.create(name: "Ballyneal G.C.", location: "Holyoke" )
Course.create(name: "Castle Pines G.C.", location: "Castle Rock")
Course.create(name: "Cherry Hills C.C.", location: "Cherry Hills Village")
Course.create(name: "Colorado G.C.", location: "Parker")
Course.create(name: "Sanctuary", location: "Sedalia")
Course.create(name: "The Broadmoor G.C", location: "Colorado Springs" )
Course.create(name: "Maroon Creek Club", location: "Aspen")
Course.create(name: "Red Sky Ranch & G.C. (Fazio)", location: "Wolcott")
Course.create(name: "Roaring Fork Club", location: "Basalt")
Course.create(name: "Red Sky Ranch & G.C. (Norman)", location: "Wolcott")
Course.create(name: "The Club At Ravenna", location: "Littleton" )
Course.create(name: "C.C. Of The Rockies", location: "Edwards")
Course.create(name: "Frost Creek G.C.", location: "Eagle")
Course.create(name: "Aspen Glen Club", location: "Carbondale")
Course.create(name: "The Club At Redlands Mesa", location: "Grand Junction")
Course.create(name: "Catamount Ranch & Club", location: "Steamboat Springs" )
Course.create(name: "Denver C.C.", location: "Denver")
Course.create(name: "The Ridge At Castle Pines North", location: "Castle Pines")
Course.create(name: "The Broadmoar G.C. (West)", location: "Colorado Springs")
Course.create(name: "The Club At Cordillera (Valley)", location: "Edwards")

Hole.create(yards: 382, par: 4, handicap: 9, course: ballyneal, tee: 1)
Hole.create(yards: 490, par: 4, handicap: 3, course: ballyneal, tee: 2)
Hole.create(yards: 145, par: 3, handicap: 17, course: ballyneal, tee: 3)
Hole.create(yards: 573, par: 5, handicap: 5, course: ballyneal, tee: 4)
Hole.create(yards: 165, par: 3, handicap: 13, course: ballyneal, tee: 5)
Hole.create(yards: 480, par: 4, handicap: 1, course: ballyneal, tee: 6)
Hole.create(yards: 352, par: 4, handicap: 15, course: ballyneal, tee: 7)
Hole.create(yards: 515, par: 5, handicap: 7, course: ballyneal, tee: 8)
Hole.create(yards: 362, par: 4, handicap: 11, course: ballyneal, tee: 9)
Hole.create(yards: 509, par: 4, handicap: 2, course: ballyneal, tee: 10)
Hole.create(yards: 200, par: 3, handicap: 18, course: ballyneal, tee: 11)
Hole.create(yards: 375, par: 4, handicap: 12, course: ballyneal, tee: 12)
Hole.create(yards: 510, par: 4, handicap: 4, course: ballyneal, tee: 13)
Hole.create(yards: 362, par: 4, handicap: 16, course: ballyneal, tee: 14)
Hole.create(yards: 237, par: 3, handicap: 14, course: ballyneal, tee: 15)
Hole.create(yards: 546, par: 5, handicap: 6, course: ballyneal, tee: 16)
Hole.create(yards: 481, par: 4, handicap: 8, course: ballyneal, tee: 17)
Hole.create(yards: 463, par: 4, handicap: 10, course: ballyneal, tee: 18)

PlayerCourse.create(player: puttmaster, course: ballyneal)