# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Player.create(username: Puttmaster1)

Course.create(name: "Ballyneal G.C.", course_location: "Holyoke" )
Course.create(name: "Castle Pines G.C.", course_location: "Castle Rock")
Course.create(name: "Cherry Hills C.C.", course_location: "Cherry Hills Village")
Course.create(name: "Colorado G.C.", course_location: "Parker")
Course.create(name: "Sanctuary", course_location: "Sedalia")
Course.create(name: "The Broadmoor G.C", course_location: "Colorado Springs" )
Course.create(name: "Maroon Creek Club", course_location: "Aspen")
Course.create(name: "Red Sky Ranch & G.C. (Fazio)", course_location: "Wolcott")
Course.create(name: "Roaring Fork Club", course_location: "Basalt")
Course.create(name: "Red Sky Ranch & G.C. (Norman)", course_location: "Wolcott")
Course.create(name: "The Club At Ravenna", course_location: "Littleton" )
Course.create(name: "C.C. Of The Rockies", course_location: "Edwards")
Course.create(name: "Frost Creek G.C.", course_location: "Eagle")
Course.create(name: "Aspen Glen Club", course_location: "Carbondale")
Course.create(name: "The Club At Redlands Mesa", course_location: "Grand Junction")
Course.create(name: "Catamount Ranch & Club", course_location: "Steamboat Springs" )
Course.create(name: "Denver C.C.", course_location: "Denver")
Course.create(name: "The Ridge At Castle Pines North", course_location: "Castle Pines")
Course.create(name: "The Broadmoar G.C. (West)", course_location: "Colorado Springs")
Course.create(name: "The Club At Cordillera (Valley)", course_location: "Edwards")

Hole.create(yards: 382, par: 4, handicap: 9, course_id: 1, tee: 1)
Hole.create(yards: 490, par: 4, handicap: 3, course_id: 1, tee: 2)
Hole.create(yards: 145, par: 3, handicap: 17, course_id: 1, tee: 3)
Hole.create(yards: 573, par: 5, handicap: 5, course_id: 1, tee: 4)
Hole.create(yards: 165, par: 3, handicap: 13, course_id: 1, tee: 5)
Hole.create(yards: 480, par: 4, handicap: 1, course_id: 1, tee: 6)
Hole.create(yards: 352, par: 4, handicap: 15, course_id: 1, tee: 7)
Hole.create(yards: 515, par: 5, handicap: 7, course_id: 1, tee: 8)
Hole.create(yards: 362, par: 4, handicap: 11, course_id: 1, tee: 9)
Hole.create(yards: 509, par: 4, handicap: 2, course_id: 1, tee: 10)
Hole.create(yards: 200, par: 3, handicap: 18, course_id: 1, tee: 11)
Hole.create(yards: 375, par: 4, handicap: 12, course_id: 1, tee: 12)
Hole.create(yards: 510, par: 4, handicap: 4, course_id: 1, tee: 13)
Hole.create(yards: 362, par: 4, handicap: 16, course_id: 1, tee: 14)
Hole.create(yards: 237, par: 3, handicap: 14, course_id: 1, tee: 15)
Hole.create(yards: 546, par: 5, handicap: 6, course_id: 1, tee: 16)
Hole.create(yards: 481, par: 4, handicap: 8, course_id: 1, tee: 17)
Hole.create(yards: 463, par: 4, handicap: 10, course_id: 1, tee: 18)